# -*- coding: utf-8 -*-
{
    'name': 'Reach Concept : Sunair Shades Structure',
    'version': '19.0.1.0.0',
    'category': 'Business Management',
    'summary': """ Reach Concept : Sunair Shades Structure """,
    'description': """ Reach Concept : Sunair Shades Structure """,
    'author': 'Reach Concept',
    'company': 'Reach Concept',
    'maintainer': 'Reach Concept',
    'website': 'https://www.reachconcept.com',

    'depends': ['base','crm','mail','sale'],

    'data': [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/dealer_application_state_data.xml",
        "data/email_templates.xml",
        "views/crm_stage_views.xml",
        "views/customer_type_views.xml",
        "views/lead_type_views.xml",
        "views/crm_territory_views.xml",
        "views/crm_lead_views.xml",
        "wizards/dealer_match_wizard_views.xml",
        "views/dealer_application_views.xml",
        "views/dealer_request_views.xml",
        "views/dealer_activity_views.xml",
        "views/dealer_request_state_views.xml",
        "views/dealer_application_state_views.xml",
        "views/dealer_status_views.xml",
        "views/product_line_views.xml",
        "views/dealer_request_form_views.xml",
        "views/crm_lead2opportunity_partner.xml",
        "views/res_partner_view.xml",
        "views/product_views.xml",
        "views/crm_product_category_views.xml",
        "views/dealer_dashboard_views.xml",
        # "views/dealer_form.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'sunair_crm/static/src/dealer_dashboard/dealer_dashboard.js',
            'sunair_crm/static/src/dealer_dashboard/dealer_dashboard.scss',
            'sunair_crm/static/src/dealer_dashboard/dealer_dashboard.xml',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}