services:
  odoo:
    container_name: sunair-odoo
    build: 
      context: .
      dockerfile: ./odoo-image/Dockerfile
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8410:8069"
      - "8411:8072" # live chat
      - "8412:8888" # debug the code
      - "8413:8889" # debug the tests
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./odoo/enterprise:/mnt/enterprise
      - ./config:/etc/odoo
    networks:
      - odoo_network
    command: >
      odoo -u sunair_crm -d april4

  postgres:
    container_name: sunair-db
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - '8414:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  odoo-data:
  postgres-data:
