from . import customer_type
from . import crm_stage
from . import lead_type
from . import crm_territory
from . import crm_lead
from . import dealer_application
from . import res_partner
from . import crm_lead2opportunity_partner
from . import product
from . import crm_product_category
from . import dealer_activity
from . import dealer_request_state
from . import dealer_request
from . import dealer_application_state
from . import product_line
from . import dealer_status